name: HURGERGAMES_ROBOZERI_HGHEROS
version: 2.9.6
api: 1.12.0
main: hungergames\main\HungerGamesPlugIn
author: Robozeri
description: Hunger Games
commands:
 hg:
  description: " Hunger Games"
  permission: mcg76.plugin.hungergames
permissions:
  plugin.hungergames:
  description: "hungergames"
  default: true
